"""init

Revision ID: be6ccfa034ef
Revises: 
Create Date: 2026-07-22 13:50:58.960953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  ## autogenerate emits sqlmodel.sql.sqltypes.* but forgets this import
import sqlmodel.sql.sqltypes  ## submodule ref needed for static analysis, lazy-loaded at runtime otherwise


# revision identifiers, used by Alembic.
revision: str = 'be6ccfa034ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pass_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SALER', 'MANAGER', 'DIRECTOR', name='role'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mgr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='salestatus'), nullable=False),
    sa.Column('join_at', sa.DateTime(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mgr_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_email'), 'sale', ['email'], unique=True)
    op.create_index(op.f('ix_sale_role'), 'sale', ['role'], unique=False)
    op.create_index(op.f('ix_sale_status'), 'sale', ['status'], unique=False)
    op.create_table('agency',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('est_year', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('loc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_code'), 'agency', ['code'], unique=True)
    op.create_index(op.f('ix_agency_owner_id'), 'agency', ['owner_id'], unique=False)
    op.create_table('assignhist',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prev_owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['new_owner_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['prev_owner_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignhist_agency_id'), 'assignhist', ['agency_id'], unique=False)
    op.create_table('oppo',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prod', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'QUALIFY', 'PROPOSE', 'NEGOTIATE', 'WON', 'LOST', name='stage'), nullable=False),
    sa.Column('loss_reason', sa.Enum('PRICE', 'COMPETITOR', 'NO_DECISION', 'POOR_FIT', 'CANCELLED', 'TIMING', name='lossreason'), nullable=True),
    sa.Column('open_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oppo_agency_id'), 'oppo', ['agency_id'], unique=False)
    op.create_index(op.f('ix_oppo_owner_id'), 'oppo', ['owner_id'], unique=False)
    op.create_index(op.f('ix_oppo_stage'), 'oppo', ['stage'], unique=False)
    op.create_index('ix_oppo_stage_open_at', 'oppo', ['stage', 'open_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_oppo_stage_open_at', table_name='oppo')
    op.drop_index(op.f('ix_oppo_stage'), table_name='oppo')
    op.drop_index(op.f('ix_oppo_owner_id'), table_name='oppo')
    op.drop_index(op.f('ix_oppo_agency_id'), table_name='oppo')
    op.drop_table('oppo')
    op.drop_index(op.f('ix_assignhist_agency_id'), table_name='assignhist')
    op.drop_table('assignhist')
    op.drop_index(op.f('ix_agency_owner_id'), table_name='agency')
    op.drop_index(op.f('ix_agency_code'), table_name='agency')
    op.drop_table('agency')
    op.drop_index(op.f('ix_sale_status'), table_name='sale')
    op.drop_index(op.f('ix_sale_role'), table_name='sale')
    op.drop_index(op.f('ix_sale_email'), table_name='sale')
    op.drop_table('sale')
    # ### end Alembic commands ###
